### PR TITLE
Initial NuGet packing scripts

### PR DESCRIPTION
**Pull request by marcusoftnet**
Ok - this became a long one... I was planning on doing 3 small drops but for some reason GitHub package it into one biggie. Sorry for that.

Updated the VersionInfo and AssemblyInfo to be better prepared for NuGet packaging. That means that I've move more attributes into the VersionInfo.cs and hence removed a few from the different AssemblyInfo.cs files. 

Also I changed the name of the console runner output (:S) since the NuGet package is created from the script. 

In the root there is a NuGetPackAll.cmd that will run all the NuGet package commands and create .nupkg. 

These files can be used locally (see for example: ) to try things out. It's a small and simple thing to create a NuGetPush.cmd for each of the packages later, but that is a bit scary :) So let's start with this, right?

I finally added all those test features I talked about earlier. So now we have 46 scenarios to test on.

### CODE REVIEW

**Comment by marcusoftnet** [comment]
I don't want to add more to this now - but I have also fixed up some unit tests - please let me know when you are ready for them.

**Comment by x97mdr** [comment]
Thanks Marcus. I will merge this Monday or Tuesday when I get back

**Comment by x97mdr** [comment]
Thanks Marcus, everything merged successfully

**Comment by marcusoftnet** [comment]
Whoho

/Marcus Hammarberg
www.marcusoft.net 
Skickat från Marcus iPhone

29 nov 2011 kl. 14:59 skrev x97mdrreply@reply.github.com:

**Pull request merged**
