### PR TITLE
Collapse/Expand Table of Content

### PR DESCRIPTION
**Pull request by dirkrombauts**
Hi,

I whipped up a quick version of a collapsible table of content.

Dirk

### CODE REVIEW

**Comment by x97mdr** [comment]
Works great!  Thanks so much!

**Comment by x97mdr** [comment]
Do you have any experience with Javascript MVC frameworks?

**Comment by dirkrombauts** [comment]
Sorry, no experience there.  I recently started with Knockout.js, but that's more MVVM than MVC.

**Comment by x97mdr** [comment]
If you take a peek at my pickles-viewer project you'll see I'm trying to
build some more dynamic documentation for Pickles.  Pickles writes out JSON
and I use Knockout to display the JSON to the user.  The idea is that we
can do more interesting things (tag clouds, filtering features, searching,
etc.) with this platform.

Would you be interested to help out there?

On Fri, Mar 9, 2012 at 2:07 AM, dirkrombauts <
reply@reply.github.com

**Comment by dirkrombauts** [comment]
Sounds interesting!  I was thinking "I'd like to search by tags in the generated HTML" the other day.

Is there a task board or something like that to discuss particular features?

**Comment by x97mdr** [comment]
Just the discussion group.  Marcus and I were using Trello for a little
while too like a mini-kanban board to track progress:
https://trello.com/board/pickles/4f076ae67519465b0715af9c

Any suggestions for a better forum?

On Fri, Mar 9, 2012 at 8:20 AM, dirkrombauts <
reply@reply.github.com

**Comment by dirkrombauts** [comment]
Not really - I used http://agilezen.com/ for a while but they don't have multi-contributer free projects AFAIK.  I gather you stopped using trello - any special reason?

**Comment by x97mdr** [comment]
Haven't stopped using it, just haven't been able to devote as much time to
Pickles this winter unfortunately.  I updated it this morning though.  I'm
thinking about doing a release ...

On Fri, Mar 9, 2012 at 9:55 AM, dirkrombauts <
reply@reply.github.com

**Comment by x97mdr** [comment]
By the way, there is also a teamcity continuous build of pickles if you
want the latest version all packaged up ...
http://teamcity.codebetter.com/project.html;jsessionid=35062E22B684C3CEE67B6136DA97D8A0?projectId=project176&tab=projectOverview

**Comment by dirkrombauts** [comment]
Thanks - BTW, I clicked on the teamcity link and that seems to log me in using your credentials.  It says "Welcome, Jeffrey Cameron" and I can open the administration section where I can see your email address.  I didn't try to make changes but this looks a bit fishy to me.

**Comment by x97mdr** [comment]
seriously?? that is a bit fishy ... a lot fishy actually.

On Fri, Mar 9, 2012 at 10:16 AM, dirkrombauts <
reply@reply.github.com

**Comment by dirkrombauts** [comment]
I did a bit of thinking about my next contributions.  You asked me if I'd be interested to work on the dynamic pickles viewer too.  I'm interested in principle, but I would rather add some more polish to the static version (like the index.html file) first.  Otherwise I fear that my contributions would be too fragmented.  I hope that's ok for you.

**Comment by x97mdr** [comment]
Of course it's OK!  I'm happy to get any contribution, honestly.  The
static version is definitely the more used right now anyway and it can
always use some love!

On Thu, Mar 15, 2012 at 12:38 PM, dirkrombauts <
reply@reply.github.com

**Pull request merged**
