### PR TITLE
PowerShell command working in basic use case

### PR DESCRIPTION
**Pull request by marcusoftnet**
I ran out of brain juice on the NuGet package stuff... But that shouldn't be too hard. On a weekday ;)

### CODE REVIEW

**Comment by marcusoftnet** [comment]
Whew! That was a long one... Had some strange problems there for awhile - seems to work fine now though (see http://www.marcusoft.net/2011/12/creating-tools-only-nuget-package.html on how I did it)

**Comment by x97mdr** [comment]
I read your blog post, looks pretty sweet!

**Comment by x97mdr** [comment]
Thanks Marcus!  I'll get the NuGet Package up today.

**Comment by marcusoftnet** [comment]
Who - yeah. BTW - do we need all those dlls? The NuGet package is not 9.3 MB which feels quite heavy. 

I especially thought of the IKVM.*.dll? I didn't dare remove anything since I didn't know what's needed and used.
Do you?

**Comment by x97mdr** [comment]
I would have to go take a peek through the other assemblies to see what is needed specifically.  I know there are a lot of the IKVM assemblies but this is because I prefer the NuGet package over storing binaries.  I want to use ILMerge (see https://github.com/x97mdr/pickles/issues/20) to package single assemblies for all of the runners and this should help reduce the package size a lot.

**Comment by x97mdr** [comment]
oh ... in your blog post you talk about using a .nuspec file ... where is it at?

**Comment by marcusoftnet** [comment]
Doh! Not checked in. Give me a sec

Must be out of my .gitignore file... or something

Aha! It's YOUR .gitignore  - i'll update it

**Comment by marcusoftnet** [comment]
There - new pull request with small changes added

**Pull request merged**
